Update build_ios.yaml

diff --git a/.github/workflows/build_ios.yaml b/.github/workflows/build_ios.yaml
--- a/.github/workflows/build_ios.yaml
+++ b/.github/workflows/build_ios.yaml
@@ -1,45 +1,46 @@
-name: Build and Sign
+name: SherlockElf
 
 on:
+  workflow_dispatch:
   push:
-    branches:
-      - main
+    branches: ["main", "ci"]
+
+permissions:
+  contents: write
 
 jobs:
-  build:
+  ios_build:
     runs-on: macos-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+    - uses: actions/checkout@v3
 
-    - name: Set up keychain and import certificate
+    - name: Configure Git
       run: |
-        # Decode the base64 certificate stored in CERTIFICATE_P12 and save it as developer_certificate.p12
-        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12
+        git config --global user.name "GitHub Actions"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-        # Check if the certificate file is valid
-        if [ -s developer_certificate.p12 ]; then
-          echo "Certificate file is valid."
-        else
+    - name: Decode the base64 certificate and save it as developer_certificate.p12
+      run: |
+        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12
+        if [ ! -s developer_certificate.p12 ]; then
           echo "Certificate file is invalid or empty."
           exit 1
+        else
+          echo "Certificate file is valid."
         fi
-        
-        # Unlock the keychain
-        security unlock-keychain -p "$KEYCHAIN_PASSWORD" /Users/runner/Library/Keychains/login.keychain-db
-        
-        # Import the developer_certificate.p12 into the keychain
-        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain-db -P "$P12_PASSWORD" -T /usr/bin/codesign
-        
-        # Set keychain settings and access permissions
-        security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain-db
-        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" /Users/runner/Library/Keychains/login.keychain-db
-        
-        # Clean up the certificate file
-        rm developer_certificate.p12
-      env:
-        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
 
-    # Continue with build, sign, and deploy steps...
+    - name: Test import the certificate into keychain
+      run: |
+        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign || echo "Import failed, possibly due to incorrect password."
+
+    - name: Exit if import fails
+      if: failure()
+      run: exit 1
+
+    - name: Continue with build process if import succeeds
+      shell: bash
+      run: |
+        echo "Proceeding with the build process as the certificate was imported successfully."
+        # Weitere Build-Schritte hier
+
