Update build_ios.yaml

diff --git a/.github/workflows/build_ios.yaml b/.github/workflows/build_ios.yaml
--- a/.github/workflows/build_ios.yaml
+++ b/.github/workflows/build_ios.yaml
@@ -20,26 +20,23 @@ jobs:
         git config --global user.name "GitHub Actions"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-    - name: Set IOS_CERTID environment variable
-      run: echo "IOS_CERTID=${{ secrets.IOS_CERTID }}" >> $GITHUB_ENV
-
-    - name: Install Dependencies
+    - name: Decode the base64 certificate and save it as developer_certificate.p12
       run: |
-        brew update
-        brew install ninja meson python@3.12
-        brew install openssl@1.1
-        brew unlink openssl@3 || true  # Unlink OpenSSL 3, if installed
-        brew link openssl@1.1 --overwrite  # Link OpenSSL 1.1 and overwrite any conflicts
-        sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $(brew --prefix openssl@1.1)/etc/openssl@1.1/cert.pem || true
+        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12
+        if [ ! -s developer_certificate.p12 ]; then
+          echo "Certificate file is invalid or empty."
+          exit 1
+        else
+          echo "Certificate file is valid."
+        fi
 
-    - name: Import the certificate and private key
+    - name: Import the certificate into keychain
       run: |
-        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
-        security unlock-keychain -p "${{ secrets.CERTIFICATE_PASSWORD }}" ~/Library/Keychains/login.keychain-db
-        security import certificate.p12 -k ~/Library/Keychains/login.keychain-db -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
-        rm certificate.p12
-      env:
-        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
+        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign || echo "Import failed, possibly due to incorrect password."
+
+    - name: Exit if import fails
+      if: failure()
+      run: exit 1
 
     - name: Clone Frida repository with submodules
       run: |
@@ -60,25 +57,31 @@ jobs:
           exit 1
         fi
 
-    - name: Build Frida server for iOS
+    - name: Build Frida Gadget and Frida Server for iOS
       shell: bash
       run: |
         mkdir -p build-ios-arm64
         cd build-ios-arm64
         ../frida/configure --host=ios-arm64
-        ninja || { echo "Build failed for ios-arm64"; ls -alh; exit 1; }
+        ninja subprojects/frida-core/lib/gadget/frida-gadget.dylib subprojects/frida-core/server/frida-server || { echo "Build failed for ios-arm64"; ls -alh; exit 1; }
 
-    - name: Code Sign Frida Helper
-      run: |
-        security unlock-keychain -p "${{ secrets.CERTIFICATE_PASSWORD }}" ~/Library/Keychains/login.keychain-db
-        /usr/bin/codesign -f -s "${{ secrets.IOS_CERTID }}" --keychain ~/Library/Keychains/login.keychain-db --entitlements ../../../../../../frida/subprojects/frida-core/src/darwin/frida-helper.xcent src/frida-helper.tmp
-
-    - name: Package frida-server for iOS
+    - name: Package Frida Gadget and Frida Server for iOS
       shell: bash
       run: |
+        gzip build-ios-arm64/subprojects/frida-core/lib/gadget/frida-gadget.dylib
         gzip build-ios-arm64/subprojects/frida-core/server/frida-server
 
-    - name: Upload iOS arm64 frida-server for SherlockElf
+    - name: Upload iOS arm64 Frida Gadget for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-arm64/subprojects/frida-core/lib/gadget/frida-gadget.dylib.gz
+        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-arm64.dylib.gz
+        asset_content_type: application/octet-stream
+
+    - name: Upload iOS arm64 Frida Server for SherlockElf
       uses: actions/upload-release-asset@v1.0.2
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
