Update workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,7 +12,7 @@ on:
 permissions:
   contents: write
 
-jobs: 
+jobs:
   check_version:
     runs-on: ubuntu-22.04
     outputs:
@@ -29,9 +29,7 @@ jobs:
               owner: 'frida',
               repo: 'frida',
             })
-            const {
-              data: { tag_name: ver }
-            } = releaseResponse;
+            const { data: { tag_name: ver } } = releaseResponse;
             core.setOutput('FRIDA_VERSION', ver);
 
       - name: Split Repository Name
@@ -55,24 +53,20 @@ jobs:
                 repo: '${{ steps.split_name.outputs.repo }}',
                 tag: releaseVersion
               });
-              const {
-                data: { tag_name: ver }
-              } = releaseResponse;
+              const { data: { tag_name: ver } } = releaseResponse;
               if (ver == '${{ steps.pullFridaLatestRelease.outputs.FRIDA_VERSION }}'){
                   if ( ${{ ( github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}){
                     core.setOutput('ALREADY_RELEASE', '2');
                   } else {
                     core.setOutput('ALREADY_RELEASE', '1');
                   }
-              }
-              else{
+              } else {
                   core.setOutput('ALREADY_RELEASE', '0');
               }
             } catch (e) {
-              if(e.message == 'Not Found'){
+              if (e.message == 'Not Found') {
                 core.setOutput('ALREADY_RELEASE', '0');
-              }
-              else{
+              } else {
                 core.setFailed(e.message);
               }
             }
@@ -117,24 +111,24 @@ jobs:
       id: setup-ndk
       uses: nttld/setup-ndk@v1
       with:
-        ndk-version: r25b  # Specify NDK r25b
+        ndk-version: r25b
 
     - name: Clone Frida repository with submodules
       run: |
         git clone --recurse-submodules https://github.com/frida/frida
         cd frida
-        git submodule update --init --recursive  # Ensure all submodules are initialized
+        git submodule update --init --recursive
 
     - name: Apply patches to frida-core
       shell: bash
       run: |
-        if [ -d "subprojects/frida-core" ]; then
-          cd subprojects/frida-core
+        if [ -d "frida/subprojects/frida-core" ]; then
+          cd frida/subprojects/frida-core
           for patch in ${{ github.workspace }}/patches/frida-core/*.patch; do
             git am "$patch"
           done
         else
-          echo "Directory subprojects/frida-core does not exist"
+          echo "Directory frida/subprojects/frida-core does not exist"
           exit 1
         fi
 
@@ -173,9 +167,7 @@ jobs:
               repo: '${{ steps.split_name.outputs.repo }}',
               tag: releaseVersion
             })
-            const {
-              data: { id: releaseId, html_url: htmlUrl, upload_url: uploadUrl }
-            } = releaseResponse;
+            const { data: { id: releaseId, html_url: htmlUrl, upload_url: uploadUrl } } = releaseResponse;
             core.setOutput('id', releaseId);
             core.setOutput('html_url', htmlUrl);
             core.setOutput('upload_url', uploadUrl);
@@ -184,7 +176,7 @@ jobs:
             core.setFailed(e.message);
           }
 
-    - name: package build result for Android
+    - name: Package build result for Android
       shell: bash
       run: |
         gzip build-android-arm/subprojects/frida-core/server/frida-server
@@ -207,9 +199,9 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
-        asset_path: '${{ github.workspace }}/build-android-arm/subprojects/frida-core/server/frida-server.gz'
-        asset_name: 'SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.gz'
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-arm/subprojects/frida-core/server/frida-server.gz
+        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.gz
         asset_content_type: application/octet-stream
 
     - name: Upload android arm64 frida-server for SherlockElf
@@ -217,9 +209,9 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
-        asset_path: '${{ github.workspace }}/build-android-arm64/subprojects/frida-core/server/frida-server.gz'
-        asset_name: 'SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.gz'
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-arm64/subprojects/frida-core/server/frida-server.gz
+        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.gz
         asset_content_type: application/octet-stream
 
     - name: Upload android x86 frida-server for SherlockElf
@@ -227,9 +219,9 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
-        asset_path: '${{ github.workspace }}/build-android-x86/subprojects/frida-core/server/frida-server.gz'
-        asset_name: 'SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.gz'
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-x86/subprojects/frida-core/server/frida-server.gz
+        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.gz
         asset_content_type: application/octet-stream
 
     - name: Upload android x86_64 frida-server for SherlockElf
@@ -237,9 +229,9 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        upload_url: '${{ steps.checkReleaseVersion.outputs.upload_url }}'
-        asset_path: '${{ github.workspace }}/build-android-x86_64/subprojects/frida-core/server/frida-server.gz'
-        asset_name: 'SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.gz'
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-x86_64/subprojects/frida-core/server/frida-server.gz
+        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.gz
         asset_content_type: application/octet-stream
         
     - name: Upload android arm frida-inject for SherlockElf
@@ -247,4 +239,231 @@ jobs:
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-        upload_url
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-arm/subprojects/frida-core/inject/frida-inject.gz
+        asset_name: SherlockElf-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.gz
+        asset_content_type: application/octet-stream
+        
+    - name: Upload android arm64 frida-inject for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-arm64/subprojects/frida-core/inject/frida-inject.gz
+        asset_name: SherlockElf-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.gz
+        asset_content_type: application/octet-stream
+        
+    - name: Upload android x86 frida-inject for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-x86/subprojects/frida-core/inject/frida-inject.gz
+        asset_name: SherlockElf-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.gz
+        asset_content_type: application/octet-stream
+        
+    - name: Upload android x86_64 frida-inject for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-x86_64/subprojects/frida-core/inject/frida-inject.gz
+        asset_name: SherlockElf-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.gz
+        asset_content_type: application/octet-stream
+    
+    - name: Upload android arm frida-gadget for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-arm/subprojects/frida-core/lib/gadget/frida-gadget.so.gz
+        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm.so.gz
+        asset_content_type: application/octet-stream
+
+    - name: Upload android arm64 frida-gadget for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-arm64/subprojects/frida-core/lib/gadget/frida-gadget.so.gz
+        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-arm64.so.gz
+        asset_content_type: application/octet-stream
+   
+    - name: Upload android x86 frida-gadget for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-x86/subprojects/frida-core/lib/gadget/frida-gadget.so.gz
+        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86.so.gz
+        asset_content_type: application/octet-stream
+
+    - name: Upload android x86_64 frida-gadget for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-android-x86_64/subprojects/frida-core/lib/gadget/frida-gadget.so.gz
+        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-android-x86_64.so.gz
+        asset_content_type: application/octet-stream
+
+  ios_build:
+    runs-on: macos-latest
+    needs: [check_version, create_release]
+
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: Configure Git
+      run: |
+        git config --global user.name "GitHub Actions"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+    - name: Install Dependencies
+      run: |
+        brew update
+        brew install ninja
+        brew install meson
+        brew install python@3.12
+        sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $(brew --prefix openssl@1.1)/etc/openssl@1.1/cert.pem
+
+    - name: Clone Frida repository with submodules
+      run: |
+        git clone --recurse-submodules https://github.com/frida/frida
+        cd frida
+        git submodule update --init --recursive
+
+    - name: Apply patches to frida-core
+      shell: bash
+      run: |
+        if [ -d "frida/subprojects/frida-core" ]; then
+          cd frida/subprojects/frida-core
+          for patch in ${{ github.workspace }}/patches/frida-core/*.patch; do
+            git am "$patch"
+          done
+        else
+          echo "Directory frida/subprojects/frida-core does not exist"
+          exit 1
+        fi
+
+    - name: Build Frida for iOS
+      shell: bash
+      run: |
+        ARCHES="ios-arm64 ios-x86_64"
+        for ARCH in $ARCHES
+        do
+          mkdir build-$ARCH
+          cd build-$ARCH
+          ../frida/configure --host=$ARCH
+          make || { echo "Build failed for $ARCH"; exit 1; }
+          cd ..
+        done
+
+    - name: Split Repository Name
+      id: split_name
+      run: |
+        repo_name=${{ github.repository }}
+        IFS='/' read -ra repo_parts <<< "$repo_name"
+        echo "owner=${repo_parts[0]}" >> $GITHUB_OUTPUT
+        echo "repo=${repo_parts[1]}" >> $GITHUB_OUTPUT
+
+    - name: Check release version
+      id: checkReleaseVersion
+      uses: actions/github-script@v3
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        script: |
+          try {
+            const releaseVersion = '${{ needs.check_version.outputs.FRIDA_VERSION }}'
+            const releaseResponse = await github.repos.getReleaseByTag({
+              owner: '${{ steps.split_name.outputs.owner }}',
+              repo: '${{ steps.split_name.outputs.repo }}',
+              tag: releaseVersion
+            })
+            const { data: { id: releaseId, html_url: htmlUrl, upload_url: uploadUrl } } = releaseResponse;
+            core.setOutput('id', releaseId);
+            core.setOutput('html_url', htmlUrl);
+            core.setOutput('upload_url', uploadUrl);
+            core.setOutput('version', releaseVersion);
+          } catch (e) {
+            core.setFailed(e.message);
+          }
+
+    - name: Package build result for iOS
+      shell: bash
+      run: |
+        gzip build-ios-arm64/subprojects/frida-core/server/frida-server
+        gzip build-ios-x86_64/subprojects/frida-core/server/frida-server
+
+        gzip build-ios-arm64/subprojects/frida-core/inject/frida-inject
+        gzip build-ios-x86_64/subprojects/frida-core/inject/frida-inject
+
+        gzip build-ios-arm64/subprojects/frida-core/lib/gadget/frida-gadget.dylib
+        gzip build-ios-x86_64/subprojects/frida-core/lib/gadget/frida-gadget.dylib
+
+    - name: Upload iOS arm64 frida-server for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-arm64/subprojects/frida-core/server/frida-server.gz
+        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-arm64.gz
+        asset_content_type: application/octet-stream
+
+    - name: Upload iOS x86_64 frida-server for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-x86_64/subprojects/frida-core/server/frida-server.gz
+        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-x86_64.gz
+        asset_content_type: application/octet-stream
+        
+    - name: Upload iOS arm64 frida-inject for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-arm64/subprojects/frida-core/inject/frida-inject.gz
+        asset_name: SherlockElf-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-arm64.gz
+        asset_content_type: application/octet-stream
+        
+    - name: Upload iOS x86_64 frida-inject for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-x86_64/subprojects/frida-core/inject/frida-inject.gz
+        asset_name: SherlockElf-inject-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-x86_64.gz
+        asset_content_type: application/octet-stream
+        
+    - name: Upload iOS arm64 frida-gadget for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-arm64/subprojects/frida-core/lib/gadget/frida-gadget.dylib.gz
+        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-arm64.dylib.gz
+        asset_content_type: application/octet-stream
+
+    - name: Upload iOS x86_64 frida-gadget for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-x86_64/subprojects/frida-core/lib/gadget/frida-gadget.dylib.gz
+        asset_name: SherlockElf-gadget-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-x86_64.dylib.gz
+        asset_content_type: application/octet-stream
