Update build_ios.yaml

diff --git a/.github/workflows/build_ios.yaml b/.github/workflows/build_ios.yaml
--- a/.github/workflows/build_ios.yaml
+++ b/.github/workflows/build_ios.yaml
@@ -20,8 +20,34 @@ jobs:
         git config --global user.name "GitHub Actions"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-    - name: Set IOS_CERTID environment variable
-      run: echo "IOS_CERTID=${{ secrets.IOS_CERTID }}" >> $GITHUB_ENV
+    - name: Set up keychain and import certificate
+      run: |
+        # Decode the base64 certificate stored in CERTIFICATE_P12 and save it as developer_certificate.p12
+        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12
+
+        # Check if the certificate file is valid
+        if [ -s developer_certificate.p12 ]; then
+          echo "Certificate file is valid."
+        else
+          echo "Certificate file is invalid or empty."
+          exit 1
+        fi
+        
+        # Unlock the keychain
+        security unlock-keychain -p "$KEYCHAIN_PASSWORD" /Users/runner/Library/Keychains/login.keychain-db
+        
+        # Import the developer_certificate.p12 into the keychain
+        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain-db -P "$P12_PASSWORD" -T /usr/bin/codesign
+        
+        # Set keychain settings and access permissions
+        security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain-db
+        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" /Users/runner/Library/Keychains/login.keychain-db
+        
+        # Clean up the certificate file
+        rm developer_certificate.p12
+      env:
+        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
 
     - name: Install Dependencies
       run: |
@@ -31,14 +57,6 @@ jobs:
         brew unlink openssl@3 || true  # Unlink OpenSSL 3, if installed
         brew link openssl@1.1 --overwrite  # Link OpenSSL 1.1 and overwrite any conflicts
         sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $(brew --prefix openssl@1.1)/etc/openssl@1.1/cert.pem || true
-
-    - name: Import the certificate and private key
-      run: |
-        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
-        security unlock-keychain -p "$KEYCHAIN_PASSWORD" ~/Library/Keychains/login.keychain-db
-        security import certificate.p12 -k ~/Library/Keychains/login.keychain-db -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
-        security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.CERTIFICATE_PASSWORD }}" ~/Library/Keychains/login.keychain-db
-        rm certificate.p12
 
     - name: Clone Frida repository with submodules
       run: |
