Update build_ios.yaml

diff --git a/.github/workflows/build_ios.yaml b/.github/workflows/build_ios.yaml
--- a/.github/workflows/build_ios.yaml
+++ b/.github/workflows/build_ios.yaml
@@ -1,4 +1,4 @@
-name: SherlockElf
+name: SherlockElf iOS
 
 on:
   workflow_dispatch:
@@ -20,27 +20,64 @@ jobs:
         git config --global user.name "GitHub Actions"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-    - name: Decode the base64 certificate and save it as developer_certificate.p12
+    - name: Set IOS_CERTID environment variable
+      run: echo "IOS_CERTID=${{ secrets.IOS_CERTID }}" >> $GITHUB_ENV
+
+    - name: Install Dependencies
       run: |
-        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > developer_certificate.p12
-        if [ ! -s developer_certificate.p12 ]; then
-          echo "Certificate file is invalid or empty."
-          exit 1
-        else
-          echo "Certificate file is valid."
-        fi
+        brew update
+        brew install ninja meson python@3.12
+        brew install openssl@1.1
+        brew unlink openssl@3 || true  # Unlink OpenSSL 3, if installed
+        brew link openssl@1.1 --overwrite  # Link OpenSSL 1.1 and overwrite any conflicts
+        sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain $(brew --prefix openssl@1.1)/etc/openssl@1.1/cert.pem || true
 
-    - name: Test import the certificate into keychain
+    - name: Import the certificate and private key
       run: |
-        security import developer_certificate.p12 -k ~/Library/Keychains/login.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign || echo "Import failed, possibly due to incorrect password."
+        echo "${{ secrets.CERTIFICATE_P12 }}" | base64 --decode > certificate.p12
+        security unlock-keychain -p "$KEYCHAIN_PASSWORD" ~/Library/Keychains/login.keychain-db
+        security import certificate.p12 -k ~/Library/Keychains/login.keychain-db -P "${{ secrets.CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
+        security set-key-partition-list -S apple-tool:,apple: -s -k "${{ secrets.CERTIFICATE_PASSWORD }}" ~/Library/Keychains/login.keychain-db
+        rm certificate.p12
 
-    - name: Exit if import fails
-      if: failure()
-      run: exit 1
+    - name: Clone Frida repository with submodules
+      run: |
+        git clone --recurse-submodules https://github.com/frida/frida
+        cd frida
+        git submodule update --init --recursive
 
-    - name: Continue with build process if import succeeds
+    - name: Apply patches to frida-core
       shell: bash
       run: |
-        echo "Proceeding with the build process as the certificate was imported successfully."
-        # Weitere Build-Schritte hier
+        if [ -d "frida/subprojects/frida-core" ]; then
+          cd frida/subprojects/frida-core
+          for patch in ${{ github.workspace }}/patches/frida-core/*.patch; do
+            git am "$patch"
+          done
+        else
+          echo "Directory frida/subprojects/frida-core does not exist"
+          exit 1
+        fi
 
+    - name: Build Frida server for iOS
+      shell: bash
+      run: |
+        mkdir -p build-ios-arm64
+        cd build-ios-arm64
+        ../frida/configure --host=ios-arm64
+        ninja || { echo "Build failed for ios-arm64"; ls -alh; exit 1; }
+
+    - name: Package frida-server for iOS
+      shell: bash
+      run: |
+        gzip build-ios-arm64/subprojects/frida-core/server/frida-server
+
+    - name: Upload iOS arm64 frida-server for SherlockElf
+      uses: actions/upload-release-asset@v1.0.2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.checkReleaseVersion.outputs.upload_url }}
+        asset_path: ${{ github.workspace }}/build-ios-arm64/subprojects/frida-core/server/frida-server.gz
+        asset_name: SherlockElf-server-${{ needs.check_version.outputs.FRIDA_VERSION }}-ios-arm64.gz
+        asset_content_type: application/octet-stream
